<template>
  <br><br>
  <div class="details">
   <p style="font-size: 30px;"><b>Give the informations  for the article you want to add : <span></span></b></p><br><br>
       <label><span><b>The title : <input v-model="updatedData.title" type="text"></b></span><br><br><br></label>
       <label><span><b> The body : <input v-model="updatedData.body" type="textarea"></b></span><br><br><br></label>
       <label><span><b>The creation date : <input v-model= "updatedData.createdAt" type="date"></b></span><br><br><br></label>
       <label><span><b>The modification data : <input v-model="updatedData.modifiedAt" type="date"></b></span><br><br><br></label>
       <label><span><b>The Tags : <input v-model="stri" type="text" placeholder="Separate with commas,"></b></span><br><br><br></label>
  </div><br><br>
  <button class="redirect"@click="func()">Save</button>
  <router-link to="/Home" class="no-underline"><button  class="redirect1">Annulate</button></router-link>

</template>

<script>
import { projectFirestore } from "../firebase/config";

export default {
name: 'ADD',
data() {
  return {
    stri : "",
    updatedData: {
      id: "",
      title: "",
      body: "",
      createdAt : "",
      modifiedAt : "",
      snippet : "",
      tags : []
    },
    error: null
  };
},
methods: {
  async func() {
    if (this.updatedData.title == "") alert(" You should fill the title");
    else if (this.updatedData.body == "") alert(" You should fill the body");
    else if (this.updatedData.stri == "") alert(" You should fill the tags");
    else if (this.updatedData.createdAt == "") alert(" You should fill the date of creation");
    else if (this.updatedData.modifiedAt == "") alert(" You should fill the date of modification");
    else if (this.stri == "") alert(" You should fill the tags");

    else {
      try {
        const docRef = await projectFirestore.collection('articles').add(this.updatedData);
        const addedId = docRef.id; // Extract the ID from docRef

        // Create a reference to the newly added document
        const newDocRef = projectFirestore.collection('articles').doc(addedId);

        // Update the document with the new ID
        await newDocRef.set({
          id: addedId, // Use the same ID as the autogenerated ID
          title: this.updatedData.title,
          body: this.updatedData.body,
          createdAt: this.updatedData.createdAt,
          modifiedAt: this.updatedData.modifiedAt,
          tags : this.stri.split(',').map(tag => tag.trim()),
          snippet : this.updatedData.body.substring(0, 50)
        });

        this.updatedData.id = "";
        this.updatedData.title = "";
        this.updatedData.body = "";
        this.updatedData.createdAt  = "";
        this.updatedData.modifiedAt = "";
        this.updatedData.snippet = "";
        this.updatedData.tags = [];
        this.$router.push({ name: 'Home' });
      } catch (err) {
        this.error = err.message;
      }
    }
  }
}
};
</script>



<style>
.details{
   border: groove;
   border-color: rgb(238, 56, 56);
   border-width: 20px;
   width: 70%;
   margin-left: 15%
   
}
.redirect{
   background-color: rgb(250, 66, 66); 
   color: #fff; /* White text */
   border: none;
   padding: 10px 20px;
   border-radius: 5px;
   cursor: pointer;
   font-size: 16px;
}
.no-underline{
      text-decoration: none;
      color: white
  }
</style>
